image: node:18

pipelines:
  default:
    - step:
        name: Test
        caches:
          - node
        script:
          - npm install
          - npm test

    - step:
        name: Build and Push Docker
        services:
          - docker
        caches:
          - docker
        script:
          # Login to Docker registry
          - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin $DOCKER_REGISTRY
          
          # Build Docker image
          - docker build -t $DOCKER_REGISTRY/markdown-editor:$BITBUCKET_COMMIT .
          - docker tag $DOCKER_REGISTRY/markdown-editor:$BITBUCKET_COMMIT $DOCKER_REGISTRY/markdown-editor:latest
          
          # Push Docker images
          - docker push $DOCKER_REGISTRY/markdown-editor:$BITBUCKET_COMMIT
          - docker push $DOCKER_REGISTRY/markdown-editor:latest

definitions:
  services:
    docker:
      memory: 2048